Solve linear systems using straightforward methods (Book 1, p. 94, ex. 11.5).

In [1]:
import numpy as np

# Common parts

In [2]:
def residual(A, b, x):
    """Calculating solution error.

    Returns:
        res_ver (ndarray): b - Ax
    """
    res_vec = b - np.dot(A, x)
    return res_vec

In [3]:
# Initial test matrix.
A = np.array([[7.35272,  0.88255,  -2.270052],
              [0.88255,  5.58351,  0.528167],
              [-2.27005, 0.528167, 4.430329]])

# Test matrix where c[0][0] = a[0][0]*10^(-8)
C = np.array([[7.35272e-8,  0.88255,  -2.270052],
              [0.88255,     5.58351,  0.528167],
              [-2.27005,    0.528167, 4.430329]])

b = np.array([[1.],
              [0.],
              [0.]])

# Gaussian elimination

In [4]:
def gaussian_elimination(A, b, eps=1e-5):
    """Solving linear system using gaussian elimination.

    Args:
        A (ndarray<ndarray, ndarray>): matrix of coefficents.
        b (ndarray): vector of values.
        eps (float): all values below eps equivalent to zero.

    Returns:
        x (ndarray): solution.
    """

    # Getting matrix shape.
    n = A.shape[0]

    # Merging coefficents with values.
    Ab = np.concatenate((A, b), axis=1)
    print("\nMerged matrix: \n{}".format(Ab))

    # Making upper triangular matrix.
    for k in range(0, n):

        # Dividing all row alements after
        # diagonal element on diagonal
        # element.
        tmp = Ab[k][k]
        if np.abs(tmp) < eps:
            print("\nElement Ab[{}][{}]={} smaller than eps={}.".format(
                k, k, tmp, eps))
        for j in range(k, n + 1):
            Ab[k][j] = Ab[k][j] / tmp

        # Substracting top element multiplied
        # by 1st element in row from each
        # element.
        for i in range(k + 1, n):
            tmp = Ab[i][k]
            for j in range(k, n + 1):
                Ab[i][j] = Ab[i][j] - Ab[k][j] * tmp

    print("\nUpper triangular matrix: \n{}".format(Ab))

    # Solve equation for an upper
    # triangular matrix Ab.
    x = np.zeros((3, 1))
    for i in range(n - 1, -1, -1):
        x[i] = Ab[i][n] / Ab[i][i]
        for k in range(i - 1, -1, -1):
            Ab[k][n] -= Ab[k][i] * x[i]

    print("\nSolution: \n{}".format(x))

    # Calculating error.
    res_vec = residual(A, b, x)
    print("\nResidual vector: \n{}".format(res_vec))

    return x

### test 1

In [5]:
_ = gaussian_elimination(A, b)


Merged matrix: 
[[ 7.35272   0.88255  -2.270052  1.      ]
 [ 0.88255   5.58351   0.528167  0.      ]
 [-2.27005   0.528167  4.430329  0.      ]]

Upper triangular matrix: 
[[ 1.          0.12003041 -0.30873636  0.13600409]
 [ 0.          1.          0.14616723 -0.02191305]
 [ 0.          0.          1.          0.09032103]]

Solution: 
[[ 0.16810435]
 [-0.03511502]
 [ 0.09032103]]

Residual vector: 
[[  0.00000000e+00]
 [ -2.08166817e-17]
 [ -5.55111512e-17]]


### test 2

In [6]:
_ = gaussian_elimination(C, b)


Merged matrix: 
[[  7.35272000e-08   8.82550000e-01  -2.27005200e+00   1.00000000e+00]
 [  8.82550000e-01   5.58351000e+00   5.28167000e-01   0.00000000e+00]
 [ -2.27005000e+00   5.28167000e-01   4.43032900e+00   0.00000000e+00]]

Element Ab[0][0]=7.35272e-08 smaller than eps=1e-05.

Upper triangular matrix: 
[[  1.00000000e+00   1.20030411e+07  -3.08736359e+07   1.36004091e+07]
 [  0.00000000e+00   1.00000000e+00  -2.57215256e+00   1.13308088e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00  -3.82677011e-01]]

Solution: 
[[-0.71223358]
 [ 0.14877722]
 [-0.38267701]]

Residual vector: 
[[  0.00000000e+00]
 [  1.65219294e-09]
 [  2.11953721e-09]]
